### ISSUE TITLE
mega/crypto/cryptopp.h:26:31: fatal error: cryptopp/cryptlib.h: No such file or directory when compile with Qt 5.9.2 on Windows

### ISSUE THREAD

**Issue by lqsa00** [meganz/sdk#881]
I would like to use Mega SDK on a Qt program for Windows.
I have the Mega directory on D:
On .pro file I put: **include("D:/Mega/sdk/bindings/qt/sdk.pri")**

When compile, gives the error:
In file included from D:/Mega/sdk/include/mega/types.h:55:0,
                 from D:/Mega/sdk/include/mega/utils.h:25,
                 from D:/Mega/sdk/include/mega/attrmap.h:25,
                 from ..\..\..\..\Mega\sdk\src\attrmap.cpp:22:
D:/Mega/sdk/include/mega/crypto/cryptopp.h:26:31: fatal error: cryptopp/cryptlib.h: No such file or directory
compilation terminated.

**Comment by sergiohs84** [comment]
Please, check you have Crypto++ library installed in your system and the `cryptlib.h` is found at your include path. Thanks
