### ISSUE TITLE
fail build with openssl 1.1.0.e

### ISSUE THREAD

**Issue by sl1pkn07** [meganz/sdk#603]
sources from git

```
src/posix/net.cpp: In static member function 'static int mega::CurlHttpIO::cert_verify_callback(X509_STORE_CTX*, void*)':
src/posix/net.cpp:2276:56: error: invalid use of incomplete type 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
     if ((evp = X509_PUBKEY_get(X509_get_X509_PUBKEY(ctx->cert))))
                                                        ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:127:16: note: forward declaration of 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
 typedef struct x509_store_ctx_st X509_STORE_CTX;
                ^~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
src/posix/net.cpp:2278:29: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
         if (BN_num_bytes(evp->pkey.rsa->n) == sizeof APISSLMODULUS1 - 1
                             ^
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
src/posix/net.cpp:2279:36: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
                 && BN_num_bytes(evp->pkey.rsa->e) == sizeof APISSLEXPONENT - 1)
                                    ^
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
src/posix/net.cpp:2281:26: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
             BN_bn2bin(evp->pkey.rsa->n, buf);
                          ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
src/posix/net.cpp:2286:30: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
                 BN_bn2bin(evp->pkey.rsa->e, buf);
                              ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
src/posix/net.cpp:2301:72: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
             LOG_warn << "Public key size mismatch " << BN_num_bytes(evp->pkey.rsa->n) << " " << BN_num_bytes(evp->pkey.rsa->e);
                                                                        ^
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
src/posix/net.cpp:2301:113: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
             LOG_warn << "Public key size mismatch " << BN_num_bytes(evp->pkey.rsa->n) << " " << BN_num_bytes(evp->pkey.rsa->e);
                                                                                                                 ^
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^~~~~~~~~~~
src/posix/net.cpp:2323:75: error: invalid use of incomplete type 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
             int len = X509_NAME_get_text_by_NID (X509_get_issuer_name (ctx->cert),
                                                                           ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from ./include/mega/posix/meganet.h:28,
                 from ./include/mega.h:76,
                 from src/posix/net.cpp:22:
/usr/include/openssl/ossl_typ.h:127:16: note: forward declaration of 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
 typedef struct x509_store_ctx_st X509_STORE_CTX;
                ^~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:2565: src/posix/src_libmega_la-net.lo] Error 1
make[2]: Leaving directory '/tmp/makepkg/megasync-git/src/build'
make[1]: *** [Makefile:3043: all-recursive] Error 1
make[1]: Leaving directory '/tmp/makepkg/megasync-git/src/build'
make: *** [Makefile:1459: all] Error 2
```

greetings

**Comment by polmr** [comment]
This PR tries to correct that: https://github.com/meganz/sdk/pull/622

**Comment by sl1pkn07** [comment]
Hi. this is now in master?

greetings

**Comment by polmr** [comment]
Yes it is. Closing issue. Cheers!
