### ISSUE TITLE
Build failure with ffmpeg 4.4

### ISSUE THREAD

**Issue by pastalian** [meganz/sdk#2576]
Since ffmpeg 4.4, `AVStream.skip_to_keyframe` is no longer public. From the comments, it seems that it should not have been used in the first place.

See: https://github.com/FFmpeg/FFmpeg/commit/108864acee1d7b0cde653cee113f3001f1b8915a

### log
```
mega/src/gfx/qt.cpp:1212:18: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘skip_to_keyframe’
 1212 |     videoStream->skip_to_keyframe = true;
```

**Comment by Lucretia** [comment]
This field is now in AVStreamInternal which is an opaque pointer, internal, inside the AVStream struct.

**Comment by detetiveselvagem** [comment]
This is still a fatal error. MEGAcmd doesn't build with ffmpeg 4.4 because of this line in src/gfx/freeimage.cpp. Is there a fix, aside from just commenting out the offending line?

**Comment by lorefx** [comment]
Hi all. I stumbled across this issue on the 3.9.12 tag build on Arch Linux. 

A temporary workaround, if applicable to your case, is to launch the configuration step as
`./configure --without-freeimage `
as depicted in the readme

Sure, you'll lose those features, but at least it compiles and run

**Comment by sergiohs84** [comment]
Closing this ticket as it's obsolete. The SDK already uses FFMPEG 5.1.2 (see [here](https://github.com/meganz/sdk/blob/c94bab4183588e6171c292c0048e54b373f258d5/contrib/cmake/vcpkg_overlay_ports/ffmpeg/vcpkg.json#L3))

**Comment by ChrisLane** [comment]
@sergiohs84 ffmpeg is now on version 7.1 and compiling this SDK had another [breakage](https://github.com/meganz/sdk/pull/2614#issuecomment-1537219997) with ffmpeg 6.
Perhaps this issue should just be updated to "Build failure with ffmpeg 6" rather than closed.

Also, you missed all the other linked issues/PRs that haven't been acknowledged by Mega for the past 3 years.
It would be nice if we got feedback on these issues, otherwise people aren't going to bother reporting issues and opening PRs.

**Comment by sergiohs84** [comment]
Yep, thanks @ChrisLane for the advice. In the near future, we plan to pay more attention to the issues/PRs provided by contributors in GitHub. As part of that process, we will check the remaining issues like the one reported with ffmpeg 6.
